import numpy as np
import matplotlib.pyplot as plt


# ============================================================
# MAIN FUNCTION
# ============================================================

def WSN_mm1_theory(num_sensors, comm_radius, lambda_per_s, rho_target):
    """
    Python reconstruction of the MATLAB function:

        WSN_mm1_theory(numSensors, commRadius,
                       lambda_per_s, rho_target)

    Inputs
    ------
    num_sensors : int
        Number of sensors.

    comm_radius : float
        Communication radius of each sensor.

    lambda_per_s : float
        Event arrival rate generated by each sensor.

    rho_target : float
        Target utilization for loaded processing nodes.

    Returns
    -------
    results : dict
        Dictionary containing per-node and network results.

    avg_delay_theory : float
        Overall traffic-weighted theoretical average delay.
    """

    # --------------------------------------------------------
    # Check utilization
    # --------------------------------------------------------

    if rho_target <= 0 or rho_target >= 1:
        print(
            f"WARNING: rho_target={rho_target:.3f} "
            "is outside (0,1). Unstable."
        )

    # --------------------------------------------------------
    # 1) Build sensors + nodes
    # --------------------------------------------------------

    sensors = generate_sensors(num_sensors, comm_radius)

    nodes = generate_nodes()

    M = len(nodes)

    # --------------------------------------------------------
    # 2) Assign sensors to nearest in-range node
    # --------------------------------------------------------

    nearest_node = assign_sensors_to_nodes(sensors, nodes)

    plot_network(sensors, nodes, nearest_node)

    # --------------------------------------------------------
    # 3) True arrival rates per node
    # --------------------------------------------------------

    n_per_node = np.zeros(M, dtype=int)

    for m in range(M):
        # MATLAB:
        # n_per_node(m) = sum(nearestNode == m)
        #
        # Python uses 0-based node indices.
        n_per_node[m] = np.sum(nearest_node == m)

    # Each sensor produces lambda_per_s events/sec.
    #
    # Therefore:
    #
    # lambda_node = number_of_sensors * lambda_per_s

    lambda_node_true = n_per_node * lambda_per_s

    # --------------------------------------------------------
    # 4) Derive mu per node from target rho
    # --------------------------------------------------------

    mu_vec = np.zeros(M, dtype=float)

    has_load = lambda_node_true > 0

    # For loaded nodes:
    #
    # rho = lambda / mu
    #
    # Therefore:
    #
    # mu = lambda / rho_target

    mu_vec[has_load] = (
        lambda_node_true[has_load] / rho_target
    )

    # Unloaded nodes get arbitrary service rate of 1.
    mu_vec[~has_load] = 1.0

    # --------------------------------------------------------
    # 5) Theoretical M/M/1 metrics
    # --------------------------------------------------------

    lambda_ = lambda_node_true.copy()
    mu = mu_vec.copy()

    rho = np.zeros(M, dtype=float)

    # Start with NaN, just like MATLAB.
    W = np.full(M, np.nan)
    Wq = np.full(M, np.nan)
    L = np.full(M, np.nan)
    Lq = np.full(M, np.nan)

    for m in range(M):

        # Calculate utilization
        if mu[m] > 0:
            rho[m] = lambda_[m] / mu[m]
        else:
            rho[m] = np.nan

        # Stability check
        if (
            not np.isfinite(rho[m])
            or rho[m] <= 0
            or rho[m] >= 1
        ):
            W[m] = np.nan
            Wq[m] = np.nan
            L[m] = np.nan
            Lq[m] = np.nan

            continue

        # ----------------------------------------------------
        # M/M/1 equations
        # ----------------------------------------------------

        # Average time in system
        W[m] = 1 / (mu[m] - lambda_[m])

        # Average waiting time in queue
        Wq[m] = (
            lambda_[m]
            / (mu[m] * (mu[m] - lambda_[m]))
        )

        # Average number in system
        L[m] = lambda_[m] * W[m]

        # Average number in queue
        Lq[m] = lambda_[m] * Wq[m]

    # --------------------------------------------------------
    # Display theoretical node delays
    # --------------------------------------------------------

    print("\nAvg. Time Spent at Nodes (Queue + Service):")
    print(W)

    # --------------------------------------------------------
    # 7) Overall average delay
    # --------------------------------------------------------

    Lambda_total = np.sum(lambda_)

    if Lambda_total > 0:

        # Traffic-weighted average delay
        #
        # sum(lambda_m * W_m)
        # --------------------
        #     sum(lambda_m)

        avg_delay_theory = (
            np.sum(lambda_ * W)
            / Lambda_total
        )

    else:
        avg_delay_theory = np.nan

    # --------------------------------------------------------
    # 8) Store results
    # --------------------------------------------------------

    results = {}

    results["params"] = {
        "numSensors": num_sensors,
        "commRadius": comm_radius,
        "lambda_per_s": lambda_per_s,
        "rho_target": rho_target,
    }

    results["M"] = M
    results["nearestNode"] = nearest_node
    results["n_per_node"] = n_per_node
    results["lambda_node_true"] = lambda_
    results["mu_per_node"] = mu
    results["rho_per_node"] = rho
    results["W_per_node"] = W
    results["Wq_per_node"] = Wq
    results["L_per_node"] = L
    results["Lq_per_node"] = Lq

    # --------------------------------------------------------
    # CDF of time spent in system
    # --------------------------------------------------------

    # NOTE:
    # The original MATLAB code uses:
    #
    #     tmax = 9.0 * W(1)
    #
    # and then uses the entire rho vector in:
    #
    #     exp(-mu(1)*(1-rho).*tax)
    #
    # That appears to be an implementation issue.
    #
    # Here we interpret the apparent intention:
    # calculate the CDF for Node 1 using rho[0].

    if np.isfinite(W[0]):

        tmin = 0.0
        tmax = 9.0 * W[0]
        Nt = 100

        tax = np.linspace(tmin, tmax, Nt)

        # Exponential CDF:
        #
        # F(t) = 1 - exp[-mu(1)*(1-rho(1))*t]

        qcdfW = np.exp(
            -mu[0] * (1.0 - rho[0]) * tax
        )

        cdfW = 1.0 - qcdfW

        plt.figure(
            num="CDF of Time Spent in System by an Event"
        )

        plt.plot(
            tax,
            cdfW,
            linewidth=4
        )

        plt.grid(True)
        plt.title(
            "CDF of Time Spent in System (W) by an Event"
        )
        plt.xlabel("t")
        plt.ylabel("P(W <= t)")

        plt.ylim(0, 1.2)
        plt.xlim(0, 45)

    # --------------------------------------------------------
    # Number of sensors connected per node
    # --------------------------------------------------------

    plt.figure(
        num="Theoretical Expected Arrivals per Node"
    )

    plt.bar(
        np.arange(1, M + 1),
        results["n_per_node"],
        alpha=0.8
    )

    plt.grid(True)
    plt.xlabel("Node")
    plt.ylabel("Number of Sensors")
    plt.title("Number of Sensors Connected Per Node")

    plt.xticks(np.arange(1, M + 1))

    # --------------------------------------------------------
    # Return results
    # --------------------------------------------------------

    return results, avg_delay_theory


# ============================================================
# HELPER FUNCTION 1
# Generate sensors
# ============================================================

def generate_sensors(num_sensors, comm_radius):
    """
    Generate sensors randomly and uniformly inside
    a unit circle.
    """

    sensors = []

    for _ in range(num_sensors):

        # Random angle:
        #
        # 0 <= angle < 2*pi

        angle = 2 * np.pi * np.random.rand()

        # sqrt(rand()) produces a uniform distribution
        # over the AREA of the circle.

        r = np.sqrt(np.random.rand())

        # Convert polar -> Cartesian coordinates.

        x = r * np.cos(angle)
        y = r * np.sin(angle)

        sensors.append({
            "position": np.array([x, y]),
            "communicationRadius": comm_radius
        })

    return sensors


# ============================================================
# HELPER FUNCTION 2
# Generate processing nodes
# ============================================================

def generate_nodes():
    """
    Generate four fixed processing nodes.

    Their locations are:

        45 degrees
        135 degrees
        225 degrees
        315 degrees

    at radius 0.4.
    """

    angles_deg = np.array([
        45,
        135,
        225,
        315
    ])

    r = 0.4

    processing_nodes = []

    for angle_deg in angles_deg:

        angle_rad = np.deg2rad(angle_deg)

        x = r * np.cos(angle_rad)
        y = r * np.sin(angle_rad)

        processing_nodes.append({
            "position": np.array([x, y])
        })

    return processing_nodes


# ============================================================
# HELPER FUNCTION 3
# Assign sensors to nearest in-range node
# ============================================================

def assign_sensors_to_nodes(sensors, nodes):
    """
    Assign every sensor to its nearest processing node
    that is within communication range.

    If no node is reachable:

        nearest_node = -1

    Otherwise:

        nearest_node = index of closest reachable node

    Python uses 0-based indexing:

        Node 1 -> index 0
        Node 2 -> index 1
        Node 3 -> index 2
        Node 4 -> index 3
    """

    # --------------------------------------------------------
    # Extract coordinates
    # --------------------------------------------------------

    sensor_xy = np.array([
        sensor["position"]
        for sensor in sensors
    ])

    node_xy = np.array([
        node["position"]
        for node in nodes
    ])

    Ns = sensor_xy.shape[0]
    M = node_xy.shape[0]

    # --------------------------------------------------------
    # Calculate distance between every sensor and node
    # --------------------------------------------------------

    # sensor_xy[:, 0, None]
    #
    # Shape:
    #
    #     Ns × 1
    #
    # node_xy[:, 0]
    #
    # Shape:
    #
    #     M
    #
    # NumPy broadcasts these to:
    #
    #     Ns × M

    dx = (
        sensor_xy[:, 0, None]
        - node_xy[:, 0]
    )

    dy = (
        sensor_xy[:, 1, None]
        - node_xy[:, 1]
    )

    distances = np.sqrt(
        dx**2 + dy**2
    )

    # --------------------------------------------------------
    # Communication radius
    # --------------------------------------------------------

    comm_radii = np.array([
        sensor["communicationRadius"]
        for sensor in sensors
    ])

    # --------------------------------------------------------
    # Initialize assignments
    # --------------------------------------------------------

    # MATLAB uses 0 to mean "blocked".
    #
    # Python normally uses -1 for "no valid index".
    #
    # Therefore:
    #
    #     Python -1 = blocked
    #
    #     Python  0 = MATLAB Node 1
    #
    #     Python  1 = MATLAB Node 2
    #
    #     Python  2 = MATLAB Node 3
    #
    #     Python  3 = MATLAB Node 4

    nearest_node = np.full(
        Ns,
        -1,
        dtype=int
    )

    # --------------------------------------------------------
    # Assign each sensor
    # --------------------------------------------------------

    for i in range(Ns):

        # Which nodes are within communication range?

        in_range = np.where(
            distances[i, :] <= comm_radii[i]
        )[0]

        # ----------------------------------------------------
        # Case 1: No nodes in range
        # ----------------------------------------------------

        if len(in_range) == 0:

            nearest_node[i] = -1

        # ----------------------------------------------------
        # Case 2: Exactly one node in range
        # ----------------------------------------------------

        elif len(in_range) == 1:

            nearest_node[i] = in_range[0]

        # ----------------------------------------------------
        # Case 3: Multiple nodes in range
        # ----------------------------------------------------

        else:

            # Distances to only the reachable nodes.

            reachable_distances = distances[
                i,
                in_range
            ]

            # Find the position of the smallest distance.

            k = np.argmin(
                reachable_distances
            )

            # Convert that back to the actual node index.

            nearest_node[i] = in_range[k]

    return nearest_node


# ============================================================
# HELPER FUNCTION 4
# Plot network
# ============================================================

def plot_network(sensors, nodes, nearest_node):
    """
    Plot sensors colored according to the node they
    are assigned to, plus blocked sensors and processing
    nodes.
    """

    plt.figure()

    # --------------------------------------------------------
    # Sensor coordinates
    # --------------------------------------------------------

    sensor_xy = np.array([
        sensor["position"]
        for sensor in sensors
    ])

    M = len(nodes)

    # Similar idea to MATLAB's:
    #
    # cmap = lines(num)

    cmap = plt.colormaps["tab10"]

    # --------------------------------------------------------
    # Plot sensors belonging to each node
    # --------------------------------------------------------

    for k in range(M):

        idx = nearest_node == k

        if np.any(idx):

            plt.scatter(
                sensor_xy[idx, 0],
                sensor_xy[idx, 1],
                s=24,
                color=cmap(k),
                label=f"Node {k + 1}"
            )

    # --------------------------------------------------------
    # Plot blocked sensors
    # --------------------------------------------------------

    idx_blocked = nearest_node == -1

    if np.any(idx_blocked):

        plt.scatter(
            sensor_xy[idx_blocked, 0],
            sensor_xy[idx_blocked, 1],
            s=36,
            color="lightgray",
            marker="o",
            edgecolors="gray",
            label="Blocked (no node)"
        )

    # --------------------------------------------------------
    # Plot unit circle
    # --------------------------------------------------------

    theta = np.linspace(
        0,
        2 * np.pi,
        400
    )

    x = np.cos(theta)
    y = np.sin(theta)

    plt.plot(
        x,
        y,
        color="black"
    )

    # --------------------------------------------------------
    # Plot processing nodes
    # --------------------------------------------------------

    node_xy = np.array([
        node["position"]
        for node in nodes
    ])

    plt.plot(
        node_xy[:, 0],
        node_xy[:, 1],
        "^",
        markerfacecolor="lightgreen",
        markeredgecolor="green",
        markersize=10,
        linestyle="None"
    )

    # --------------------------------------------------------
    # Plot settings
    # --------------------------------------------------------

    plt.axis("equal")
    plt.grid(True)

    plt.title("Sensor Network")
    plt.xlabel("X position")
    plt.ylabel("Y position")

    plt.legend()


# ============================================================
# EXAMPLE RUN
# ============================================================

if __name__ == "__main__":

    results, avg_delay = WSN_mm1_theory(
        num_sensors=100,
        comm_radius=0.5,
        lambda_per_s=1.0,
        rho_target=0.8
    )

    print("\n====================================")
    print("NETWORK RESULTS")
    print("====================================")

    print(
        "Sensors per node:",
        results["n_per_node"]
    )

    print(
        "Arrival rate per node:",
        results["lambda_node_true"]
    )

    print(
        "Service rate per node:",
        results["mu_per_node"]
    )

    print(
        "Utilization per node:",
        results["rho_per_node"]
    )

    print(
        "Average time in system per node:",
        results["W_per_node"]
    )

    print(
        "Overall theoretical average delay:",
        avg_delay
    )

    plt.show()
